name: admin
description: A new Flutter project.
publish_to: 'none'


# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.19.6'

# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter 


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  window_manager: ^0.1.4
  flutter_acrylic: any
  font_awesome_flutter: ^10.4.0
  google_fonts: ^4.0.3
  fluent_ui: ^4.4.2
  dartz: ^0.10.1
  get_it: any
  flutter_mobx: any
  mobx: any
  shared_preferences: ^2.1.0
  data_table_2: ^2.4.2
  pluto_grid: ^5.4.3
  http: ^0.13.6 
  brasil_fields: any
  collection: ^1.17.0
  


dev_dependencies:
  build_runner: any
  mobx_codegen: any
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/img/
    - assets/logo/
  

